name: Restart Telegram Bot

on:
  schedule:
    - cron: '0 2 * * *' # این زمان‌بندی را می‌توانید تغییر دهید
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restart bot using API
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/sami303/files/path/home/sami303/run_restart_script.py --header 'Authorization: Token e23969fcd387b50fdc432580c028845e2249d0b8'
